version: '3'
services:
  # Service cho ứng dụng Node.js
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my-wedding-db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules 
    command: sh -c "npm run migration:deploy && npm run dev"
  # Service cho PostgreSQL
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-wedding-db
