# Sử dụng Node.js image chính thức
FROM node:18

# Thiết lập thư mục làm việc cho ứng dụng
WORKDIR /app

# Sao chép package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn của ứng dụng vào container
COPY . .

# Expose cổng mà ứng dụng sẽ chạy
EXPOSE 5000

RUN apt-get update -y && apt-get install -y openssl
RUN npx prisma generate

# Chạy lệnh để khởi động ứng dụng
# CMD ["npm", "run", "migration:deploy"]
